In [2]:
import gym 
import numpy as np 
import random 
from tqdm import tqdm

In [ ]:
env = gym.make("Taxi-v3", render_mode = "ansi")
env.reset()
print(env.render())
"""
0: Guney
1: Kuzey
2: Dogu
3: Bati
4: Yolcuyu almak
5: Yolcuyu bırakmak

"""

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+




In [7]:
action_space = env.action_space.n
state_space = env.observation_space.n
q_table = np.zeros((state_space, action_space))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
alpha = 0.1
gamma = 0.6
epsilon = 0.1 

for i in tqdm(range(1,100001)):
    state, _ = env.reset()
    done = False

    while not done :
        if random.uniform(0,1):
            action = env.action_space.sample()
        else: # exploit
            action = np.argmax(q_table[state])
        
        next_state, reward, done, info, _ = env.step(action)

        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma * np.max(q_table[state, action])-q_table[state, action])

        state = next_state
print("Traning Finished")


  0%|          | 0/100000 [00:00<?, ?it/s]c:\Users\mfurk\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
100%|██████████| 100000/100000 [1:49:21<00:00, 15.24it/s] 

Traning Finished


In [ ]:
# test
total_epoch, total_penalties = 0, 0
episodes = 100

for i in tqdm(range(episodes)):
    
    state, _ = env.reset()
    
    epochs, penalties, reward = 0, 0, 0
    
    done = False
    
    while not done:
        
        action = np.argmax(q_table[state])
    
        next_state, reward, done, info, _  = env.step(action)
                
        state = next_state
        
        if reward == -10:
            penalties += 1
            
        epochs += 1
    
    total_epoch += epochs
    total_penalties += penalties
    
print("Result after {} episodes".format(episodes))
print("Average timesteps per episode: ",total_epoch/episodes)
print("Average penalties per espisode: ",total_penalties/episodes)

###  Progress: 100% | ██████████ | 100/100 [00:00<00:00, 3999.79it/s]

##  Result after 100 Episodes
- ** Average Timesteps per Episode:** 13.29  
- ** Average Penalties per Episode:** 0.0  
